"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2, Loader2 } from "lucide-react";
import { submitForm } from "@/lib/api";

type Kind="contact"|"quotes"|"service-requests"|"applications";
export function LeadForm({kind="contact",compact=false}:{kind?:Kind;compact?:boolean}){const [status,setStatus]=useState<"idle"|"loading"|"done"|"error">("idle");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("loading");const form=new FormData(e.currentTarget);try{await submitForm(kind,form);setStatus("done");e.currentTarget.reset()}catch{setStatus("error")}}if(status==="done")return <div className="rounded-3xl bg-teal-50 p-8 text-center dark:bg-teal-950/30"><CheckCircle2 className="mx-auto text-brand-teal" size={42}/><h3 className="mt-4 text-xl font-bold text-slate-950 dark:text-white">Thank you — request received.</h3><p className="mt-2 text-sm">Our team will contact you within one business day.</p></div>;return <form onSubmit={submit} className="grid gap-5" encType="multipart/form-data"><div className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Full name" required/><Field name="company" label="Company / organisation"/><Field name="email" label="Work email" type="email" required/><Field name="phone" label="Phone number" type="tel" required/></div>{kind!=="contact"&&kind!=="applications"&&<label className="block"><span className="mb-2 block text-sm font-bold">Solution needed</span><select name="service" required className="w-full rounded-xl border border-slate-200 bg-transparent px-4 py-3 outline-none focus:border-brand-teal dark:border-slate-700"><option value="">Select a service</option><option>POS Systems</option><option>CCTV & Surveillance</option><option>Web Development</option><option>Biometric Systems</option><option>Computer Networking</option></select></label>}{kind==="applications"&&<><Field name="position" label="Position applying for" required/><label><span className="mb-2 block text-sm font-bold">CV / résumé</span><input name="cv" type="file" accept=".pdf,.doc,.docx" required className="w-full rounded-xl border border-dashed border-slate-300 p-4 text-sm dark:border-slate-700"/></label></>}<label><span className="mb-2 block text-sm font-bold">{kind==="applications"?"Cover note":"Tell us about your requirements"}</span><textarea name="message" required rows={compact?3:5} className="w-full rounded-xl border border-slate-200 bg-transparent px-4 py-3 outline-none focus:border-brand-teal dark:border-slate-700" placeholder="How can we help?"/></label><label className="flex items-start gap-3 text-xs text-slate-500"><input type="checkbox" required className="mt-0.5 accent-brand-teal"/>I agree to the privacy policy and consent to being contacted about this request.</label>{status==="error"&&<p role="alert" className="text-sm text-red-600">Something went wrong. Please call or email us, or try again.</p>}<button disabled={status==="loading"} className="btn-primary w-fit disabled:opacity-60">{status==="loading"?<Loader2 className="animate-spin" size={18}/>:<>Send request <ArrowRight size={17}/></>}</button></form>}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input name={name} type={type} required={required} className="w-full rounded-xl border border-slate-200 bg-transparent px-4 py-3 outline-none focus:border-brand-teal dark:border-slate-700"/></label>}

export function Newsletter(){const [done,setDone]=useState(false);return <form onSubmit={e=>{e.preventDefault();setDone(true)}} className="mt-8 flex max-w-xl flex-col gap-3 sm:flex-row">{done?<p className="font-bold text-white">You’re subscribed. Welcome aboard!</p>:<><label className="sr-only" htmlFor="newsletter">Email address</label><input id="newsletter" type="email" required placeholder="Your email address" className="min-w-0 flex-1 rounded-full border border-white/20 bg-white/10 px-5 py-3 text-white placeholder:text-white/50 outline-none focus:border-brand-teal"/><button className="btn-primary">Subscribe</button></>}</form>}
