import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, Check, ChevronRight, Factory, GraduationCap, HeartPulse, Hotel, ShieldCheck, ShoppingBag } from "lucide-react";
import { services, posts } from "@/lib/data";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { Stat } from "@/components/stat";
import { ProjectGrid } from "@/components/project-grid";
import { FAQ } from "@/components/faq";
import { Newsletter } from "@/components/forms";

export default function Home(){return <>
  <section className="relative min-h-[760px] overflow-hidden bg-brand-ink text-white"><Image src="/images/hero-ict.png" alt="Connected digital business infrastructure in Nairobi" fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#06132d] via-[#06132d]/85 to-transparent"/><div className="container-site relative flex min-h-[760px] items-center py-24"><div className="max-w-3xl"><p className="eyebrow text-teal-300">Kenya’s trusted ICT solutions partner</p><h1 className="font-display text-5xl font-bold leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Transforming Businesses Through <span className="text-brand-teal">Smart ICT Solutions</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">From dependable infrastructure to custom digital platforms, we help ambitious organisations work smarter, stay secure and scale with confidence.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/quote" className="btn-primary">Get a Free Quote <ArrowRight size={18}/></Link><Link href="/contact" className="btn-secondary">Contact Us</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-white/70">{["Kenya-wide support","Certified expertise","Business-first delivery"].map(x=><span key={x} className="flex items-center gap-2"><Check size={16} className="text-brand-teal"/>{x}</span>)}</div></div></div></section>

  <section className="py-20 sm:py-28"><div className="container-site grid items-center gap-14 lg:grid-cols-2"><Reveal><p className="eyebrow">Built for business</p><h2 className="heading">Technology should move your business forward.</h2><p className="mt-6 text-lg leading-8">Sysnettech Solutions brings strategy, engineering and responsive support together under one roof. We simplify complex technology and deliver solutions your team can trust every day.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 font-bold text-brand-navy hover:text-brand-teal dark:text-white">Discover our story <ArrowRight size={18}/></Link></Reveal><Reveal className="grid grid-cols-2 gap-4"><div className="card col-span-2 bg-brand-navy text-white dark:bg-brand-navy"><ShieldCheck size={36} className="text-brand-teal"/><h3 className="mt-10 font-display text-2xl font-bold">One accountable technology partner</h3><p className="mt-3 text-sm leading-6 text-white/70">Assessment, design, supply, installation, training and support—all delivered by one capable team.</p></div><div className="card"><b className="font-display text-3xl text-brand-teal">24/7</b><p className="mt-2 text-sm">Critical support options</p></div><div className="card"><b className="font-display text-3xl text-brand-orange">100%</b><p className="mt-2 text-sm">Solution-focused approach</p></div></Reveal></div></section>

  <section className="bg-slate-50 py-20 dark:bg-slate-900/50 sm:py-28"><div className="container-site"><SectionHeading eyebrow="What we do" title="End-to-end ICT solutions, built around you." copy="Practical, secure and scalable technology aligned to your goals—not one-size-fits-all packages."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Reveal key={s.slug}><Link id={s.slug} href={`/services#${s.slug}`} className={`card group block h-full ${i===0?"lg:col-span-2":""}`}><div className="flex items-start justify-between"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-brand-teal dark:bg-teal-950/50"><s.icon/></span><ChevronRight className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-brand-orange"/></div><h3 className="mt-7 font-display text-xl font-bold text-slate-950 dark:text-white">{s.title}</h3><p className="mt-3 leading-7 text-slate-600 dark:text-slate-400">{s.summary}</p><div className="mt-5 flex flex-wrap gap-2">{s.items.slice(0,i===0?5:3).map(x=><span key={x} className="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-800">{x}</span>)}</div></Link></Reveal>)}</div></div></section>

  <section className="bg-brand-navy py-16"><div className="container-site grid grid-cols-2 gap-8 lg:grid-cols-4"><Stat value={12} suffix="+" label="Years of experience"/><Stat value={350} suffix="+" label="Projects delivered"/><Stat value={98} suffix="%" label="Client satisfaction"/><Stat value={24} suffix="/7" label="Support availability"/></div></section>

  <section className="py-20 sm:py-28"><div className="container-site"><SectionHeading eyebrow="Industries" title="Context-aware solutions for every sector." center/><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{[[ShoppingBag,"Retail"],[Hotel,"Hospitality"],[GraduationCap,"Education"],[HeartPulse,"Healthcare"],[Factory,"Manufacturing"],[Building2,"Corporate"]].map(([Icon,label])=>{const I=Icon as typeof ShoppingBag;return <div className="card text-center" key={label as string}><I className="mx-auto text-brand-teal"/><b className="mt-4 block text-sm text-slate-950 dark:text-white">{label as string}</b></div>})}</div></div></section>

  <section className="bg-brand-ink py-20 text-white sm:py-28"><div className="container-site"><SectionHeading eyebrow="Selected work" title="Technology with measurable impact." copy="A selection of secure, scalable systems delivered for organisations across Kenya."/><ProjectGrid limit={3}/><div className="mt-10 text-center"><Link href="/portfolio" className="btn-secondary">Explore all projects <ArrowRight size={17}/></Link></div></div></section>

  <section className="py-20 sm:py-28"><div className="container-site"><SectionHeading eyebrow="Client stories" title="Trusted where reliability matters." center/><div className="grid gap-5 lg:grid-cols-3">{[["Sysnettech modernised our checkout and stock process without disrupting operations. Their support team is consistently responsive.","Operations Director","Retail Group"],["The CCTV rollout gave our managers reliable remote visibility across sites. The installation was tidy, documented and on schedule.","Facilities Manager","Manufacturing Company"],["Our new platform is faster, easier to manage and has improved qualified enquiries. They understood both the technical and business brief.","Managing Director","Professional Services Firm"]].map(([q,n,r])=><blockquote key={n} className="card"><div className="text-brand-orange">★★★★★</div><p className="mt-5 leading-7">“{q}”</p><footer className="mt-7"><b className="text-sm text-slate-950 dark:text-white">{n}</b><small className="block text-slate-500">{r}</small></footer></blockquote>)}</div></div></section>

  <section className="border-y border-slate-200 py-12 dark:border-slate-800"><div className="container-site"><p className="text-center text-xs font-bold uppercase tracking-[.2em] text-slate-400">Technology partners & platforms we work with</p><div className="mt-8 grid grid-cols-2 gap-6 text-center font-display text-xl font-bold text-slate-400 sm:grid-cols-3 lg:grid-cols-6">{["Microsoft","Cisco","MikroTik","Hikvision","ZKTeco","Epson"].map(x=><span key={x}>{x}</span>)}</div></div></section>

  <section className="bg-slate-50 py-20 dark:bg-slate-900/50 sm:py-28"><div className="container-site"><SectionHeading eyebrow="Insights" title="Ideas to help you make better technology decisions."/><div className="grid gap-5 lg:grid-cols-3">{posts.map(p=><article className="card" key={p.title}><small className="font-bold text-brand-teal">{p.category} · {p.date}</small><h3 className="mt-4 font-display text-xl font-bold text-slate-950 dark:text-white">{p.title}</h3><p className="mt-3 leading-7">{p.excerpt}</p><Link href="/blog" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand-navy dark:text-brand-teal">Read insight <ArrowRight size={16}/></Link></article>)}</div></div></section>

  <section className="py-20 sm:py-28"><div className="container-site"><SectionHeading eyebrow="Frequently asked" title="Straight answers before we get started." center/><FAQ/></div></section>

  <section className="bg-brand-navy py-20 text-white"><div className="container-site grid gap-10 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow text-teal-300">Stay informed</p><h2 className="font-display text-3xl font-bold sm:text-4xl">Useful ICT guidance, sent occasionally.</h2><p className="mt-4 text-white/60">No noise—just practical insights, security tips and product updates.</p><Newsletter/></div><div className="lg:text-right"><h3 className="font-display text-3xl font-bold">Ready to build what’s next?</h3><p className="mt-3 text-white/60">Tell us what you need. We’ll respond with clear next steps.</p><Link href="/quote" className="btn-primary mt-6">Request your free quote <ArrowRight size={17}/></Link></div></div></section>
  </>}
